import crypto from 'crypto';
import { logger } from '../utils/logger.js';

// In-memory session store: token -> { createdAt, lastSeen }. Sessions are lost
// on restart, which simply means admins log in again.
const authenticatedSessions = new Map();

// A session dies after SESSION_IDLE_MS without use, or SESSION_MAX_AGE_MS after
// login regardless of activity. Both are enforced on every request, not only by
// the periodic sweep.
const SESSION_IDLE_MS = 24 * 60 * 60 * 1000;      // 24 hours
const SESSION_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000; // 7 days
const MAX_SESSIONS = 50;

// Per-IP failed-login tracking. Failures within AUTH_WINDOW count towards the
// lockout; older ones are forgotten so stray typos don't accumulate forever.
const authAttempts = new Map(); // ip -> { count, firstAttempt, lockedUntil }
const MAX_AUTH_ATTEMPTS = 5;
const AUTH_WINDOW = 15 * 60 * 1000;       // 15 minutes
const AUTH_LOCKOUT_TIME = 15 * 60 * 1000; // 15 minutes

export const clientIp = (req) => req.ip || req.socket?.remoteAddress || 'unknown';

// Authless mode (NAUTILUS_AUTH_DISABLED=true): every request from a loopback or
// private-network address is treated as admin. Requests from anywhere else are
// refused, so an instance that accidentally ends up internet-facing isn't open.
let authDisabled = false;
export const setAuthDisabled = (v) => { authDisabled = !!v; };
export const isAuthDisabled = () => authDisabled;

export const isLocalAddress = (ip) => {
  if (typeof ip !== 'string') return false;
  let a = ip.toLowerCase();
  if (a.startsWith('::ffff:')) a = a.substring(7); // IPv4-mapped IPv6
  if (a === '::1') return true;
  if (/^f[cd][0-9a-f]{2}:/.test(a) || /^fe[89ab][0-9a-f]:/.test(a)) return true; // fc00::/7 ULA, fe80::/10 link-local
  const m = a.match(/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/);
  if (!m) return false;
  const [o1, o2] = [Number(m[1]), Number(m[2])];
  return o1 === 127 || o1 === 10 ||
    (o1 === 172 && o2 >= 16 && o2 <= 31) ||
    (o1 === 192 && o2 === 168) ||
    (o1 === 169 && o2 === 254);
};

const authlessAllowed = (req) => authDisabled && isLocalAddress(clientIp(req));

// Generate secure session token
export const generateSessionToken = () => {
  return crypto.randomBytes(32).toString('hex');
};

export const bearerToken = (req) => {
  const h = req.headers.authorization;
  return h && h.startsWith('Bearer ') ? h.substring(7) : null;
};

// Check if IP is currently locked out. Returns seconds remaining, or 0.
export const lockoutRemaining = (ip) => {
  const a = authAttempts.get(ip);
  if (!a || !a.lockedUntil) return 0;
  const left = a.lockedUntil - Date.now();
  if (left <= 0) {
    authAttempts.delete(ip);
    return 0;
  }
  return Math.ceil(left / 1000);
};

export const isRateLimited = (ip) => lockoutRemaining(ip) > 0;

// Record failed authentication attempt
export const recordFailedAuth = (ip) => {
  const now = Date.now();
  let a = authAttempts.get(ip);
  if (!a || now - a.firstAttempt > AUTH_WINDOW) {
    a = { count: 0, firstAttempt: now, lockedUntil: 0 };
  }
  a.count++;
  if (a.count >= MAX_AUTH_ATTEMPTS) {
    a.lockedUntil = now + AUTH_LOCKOUT_TIME;
    logger.warn(`🚫 [AUTH] ${ip} locked out for ${AUTH_LOCKOUT_TIME / 60000} min after ${a.count} failed attempts`);
  }
  authAttempts.set(ip, a);
};

// Clear successful authentication attempts
export const clearAuthAttempts = (ip) => {
  authAttempts.delete(ip);
};

const isExpired = (s, now = Date.now()) =>
  now - s.lastSeen > SESSION_IDLE_MS || now - s.createdAt > SESSION_MAX_AGE_MS;

// Register a new authenticated session (token is generated by caller).
export const registerSession = (token) => {
  // Bound memory: evict the oldest session(s) if at capacity.
  while (authenticatedSessions.size >= MAX_SESSIONS) {
    const oldest = authenticatedSessions.keys().next().value;
    authenticatedSessions.delete(oldest);
  }
  const now = Date.now();
  authenticatedSessions.set(token, { createdAt: now, lastSeen: now });
};

// Invalidate a session token (logout).
export const destroySession = (token) => {
  authenticatedSessions.delete(token);
};

// Invalidate every session (e.g. after a credential change). Returns the count.
export const destroyAllSessions = () => {
  const n = authenticatedSessions.size;
  authenticatedSessions.clear();
  return n;
};

// Returns true if the token maps to a live session, refreshing its timestamp.
export const touchSession = (token) => {
  if (!token) return false;
  const s = authenticatedSessions.get(token);
  if (!s) return false;
  const now = Date.now();
  if (isExpired(s, now)) {
    authenticatedSessions.delete(token);
    return false;
  }
  s.lastSeen = now;
  return true;
};

// True if the request may use admin features (valid session, or authless mode
// from a local address). Refreshes the session timestamp.
export const isAdminRequest = (req) => authlessAllowed(req) || touchSession(bearerToken(req));

// Middleware to authenticate requests
export const authenticateRequest = (req, res, next) => {
  if (authDisabled) {
    if (authlessAllowed(req)) return next();
    logger.warn(`🚫 [AUTH] Authless mode: refused ${req.method} ${req.path} from non-local address ${clientIp(req)}`);
    return res.status(403).json({
      error: 'Forbidden',
      message: 'Authentication is disabled on this server, so admin access is limited to local network addresses'
    });
  }

  const token = bearerToken(req);

  if (!token) {
    logger.info(`❌ [AUTH] Unauthenticated request from ${clientIp(req)} to ${req.method} ${req.path} (missing/invalid auth header)`);
    return res.status(401).json({
      error: 'Unauthorized',
      message: 'Missing or invalid authorization header'
    });
  }

  if (!touchSession(token)) {
    logger.info(`❌ [AUTH] Invalid or expired session token from ${clientIp(req)} to ${req.method} ${req.path}`);
    return res.status(401).json({
      error: 'Unauthorized',
      message: 'Invalid or expired session token'
    });
  }

  next();
};

// Periodic sweep of expired sessions and stale lockout entries.
const cleanup = () => {
  const now = Date.now();
  for (const [token, s] of authenticatedSessions.entries()) {
    if (isExpired(s, now)) authenticatedSessions.delete(token);
  }
  for (const [ip, a] of authAttempts.entries()) {
    if (now > a.lockedUntil && now - a.firstAttempt > AUTH_WINDOW) authAttempts.delete(ip);
  }
};

const timer = setInterval(cleanup, 10 * 60 * 1000);
if (timer.unref) timer.unref();
