import crypto from 'crypto';

// Session storage for authenticated sessions (in production, use Redis or database)
const authenticatedSessions = new Map();

// Rate limiting for authentication attempts
const authAttempts = new Map();
const MAX_AUTH_ATTEMPTS = 5;
const AUTH_LOCKOUT_TIME = 15 * 60 * 1000; // 15 minutes

// Generate secure session token
export const generateSessionToken = () => {
  return crypto.randomBytes(32).toString('hex');
};

// Constant-time credential comparison. Both inputs are hashed to a fixed-length
// digest first, so neither the result nor the timing leaks the secret's length.
export const safeEqual = (a, b) => {
  const ha = crypto.createHash('sha256').update(String(a)).digest();
  const hb = crypto.createHash('sha256').update(String(b)).digest();
  return crypto.timingSafeEqual(ha, hb);
};

// Check if IP is rate limited
export const isRateLimited = (ip) => {
  const attempts = authAttempts.get(ip);
  if (!attempts) return false;

  if (attempts.count >= MAX_AUTH_ATTEMPTS) {
    const timeSinceLastAttempt = Date.now() - attempts.lastAttempt;
    if (timeSinceLastAttempt < AUTH_LOCKOUT_TIME) {
      return true;
    } else {
      // Reset attempts after lockout period
      authAttempts.delete(ip);
      return false;
    }
  }

  return false;
};

// Record failed authentication attempt
export const recordFailedAuth = (ip) => {
  const attempts = authAttempts.get(ip) || { count: 0, lastAttempt: 0 };
  attempts.count++;
  attempts.lastAttempt = Date.now();
  authAttempts.set(ip, attempts);
};

// Clear successful authentication attempts
export const clearAuthAttempts = (ip) => {
  authAttempts.delete(ip);
};

// Register a new authenticated session, returning nothing (token is generated by caller).
export const registerSession = (token) => {
  authenticatedSessions.set(token, Date.now());
};

// Invalidate a session token (logout).
export const destroySession = (token) => {
  authenticatedSessions.delete(token);
};

// Returns true if the token maps to a live session, refreshing its timestamp.
export const touchSession = (token) => {
  if (authenticatedSessions.has(token)) {
    authenticatedSessions.set(token, Date.now());
    return true;
  }
  return false;
};

// Middleware to authenticate requests
export const authenticateRequest = (req, res, next) => {
  const clientIp = req.ip || req.connection.remoteAddress || req.headers['x-forwarded-for'] || 'unknown';

  const authHeader = req.headers.authorization;

  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    console.log(`❌ [AUTH] Unauthenticated request from ${clientIp} to ${req.method} ${req.path} (missing/invalid auth header)`);
    return res.status(401).json({
      error: 'Unauthorized',
      message: 'Missing or invalid authorization header'
    });
  }

  const token = authHeader.substring(7); // Remove 'Bearer ' prefix

  if (!authenticatedSessions.has(token)) {
    console.log(`❌ [AUTH] Invalid session token from ${clientIp} to ${req.method} ${req.path} (token: ${token.substring(0, 8)}...)`);
    return res.status(401).json({
      error: 'Unauthorized',
      message: 'Invalid or expired session token'
    });
  }

  // Update session timestamp
  authenticatedSessions.set(token, Date.now());
  next();
};

// Clean up expired sessions (older than 24 hours)
const cleanupExpiredSessions = () => {
  const now = Date.now();
  const maxAge = 24 * 60 * 60 * 1000; // 24 hours

  for (const [token, timestamp] of authenticatedSessions.entries()) {
    if (now - timestamp > maxAge) {
      authenticatedSessions.delete(token);
    }
  }
};

// Clean up expired sessions every hour
setInterval(cleanupExpiredSessions, 60 * 60 * 1000);
